import Head from 'next/head'
import Tab from '../components/Tab'

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>LUX | online movies rating</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Banner results={props.trending.results} /> */}
      <div className="mx-3 xl:container xl:mx-auto pt-2 pb-3">
        <Tab title="Trending this day" type={[
          {title: 'All', name: 'all', type: 'day'},
          {title: 'Movies', name: 'movie', type: 'day'},
          {title: 'TV show', name: 'tv', type: 'day'}
        ]} dataset={props.trending} isTrending={true} languages={props.languages} />
        <Tab title="What's Popular" type={[
          {title: 'Movies', name: 'movie', type: 'popular'},
          {title: 'TV show', name: 'tv', type: 'popular'}
        ]} dataset={props.popularMovies} languages={props.languages} />
        <Tab title="Now Playing" type={[
          {title: 'Movies', name: 'movie', type: 'now_playing'},
          {title: 'TV show', name: 'tv', type: 'airing_today'}
        ]} dataset={props.nowPlaying} languages={props.languages} />
        <Tab title="Top Ratings" type={[
          {title: 'Movies', name: 'movie', type: 'top_rated'},
          {title: 'TV show', name: 'tv', type: 'top_rated'}
        ]} dataset={props.topRated} languages={props.languages} />
        <Tab title="Upcoming & On Air" type={[
          {title: 'Movies', name: 'movie', type: 'upcoming'},
          {title: 'TV show', name: 'tv', type: 'on_the_air'}
        ]} dataset={props.upcomingMovies} languages={props.languages} />
      </div>
    </div>
  )
  // }
}

export async function getServerSideProps() {
  const tr = await fetch("https://api.themoviedb.org/3/movie/top_rated?api_key=f52aa1a7c260685a467d566a4b94825f")
  const topRated = await tr.json()

  const np = await fetch("https://api.themoviedb.org/3/movie/now_playing?api_key=f52aa1a7c260685a467d566a4b94825f")
  const nowPlaying = await np.json()

  const pm = await fetch("https://api.themoviedb.org/3/movie/popular?api_key=f52aa1a7c260685a467d566a4b94825f")
  const popularMovies = await pm.json()

  const upcoming = await fetch("https://api.themoviedb.org/3/movie/upcoming?api_key=f52aa1a7c260685a467d566a4b94825f")
  const upcomingMovies = await upcoming.json()

  const getTrending = await fetch("https://api.themoviedb.org/3/trending/all/day?api_key=f52aa1a7c260685a467d566a4b94825f")
  const trending = await getTrending.json()

  const reqLang = await fetch(`https://api.themoviedb.org/3/configuration/languages?api_key=f52aa1a7c260685a467d566a4b94825f`)
  const languages = await reqLang.json()

  return {
    props: {
      topRated: topRated,
      nowPlaying: nowPlaying,
      popularMovies: popularMovies,
      upcomingMovies: upcomingMovies,
      trending: trending,
      languages: languages
    },
  }
}
